apiVersion: v1
kind: Template
labels:
  template: pipeline-aplicacoes-angular
message: |-
  A Jenkins server will be automatically instantiated in this project to manage
  the Pipeline BuildConfig created by this template.  You will be able to log in to
  it using your OpenShift user credentials.
metadata:
  annotations:
    openshift.io/display-name: Pipeline Angular
    description: |-
      This example showcases the new Jenkins Pipeline integration in OpenShift,
      which performs continuous integration and deployment right on the platform.
      The template contains a Jenkinsfile - a definition of a multi-stage CI/CD process - that
      leverages the underlying OpenShift platform for dynamic and scalable
      builds. OpenShift integrates the status of your pipeline builds into the web
      console allowing you to see your entire application lifecycle in a single view.
    iconClass: icon-jenkins
    tags: instant-app,angular
  name: pipeline-aplicacoes-angular
parameters:
- description: Nome da aplicação. O nome que está inserido no package.json.
  displayName: Nome da aplicação
  name: NOME_APLICACAO
  required: true
- description: OpenShift Namespace da ImageStreams.
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: openshift
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "${NOME_APLICACAO}-pipeline", "namespace": "${NAMESPACE}", "kind": "DeploymentConfig"}]'
    labels:
      name: ${NOME_APLICACAO}-pipeline
    name: ${NOME_APLICACAO}-pipeline
  spec:
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: scripts/build-angular.groovy
    source:
      git:
        uri: "https://github.com/scripts-docker/openshift.git"